name: deploy to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        GODOT_VERSION: [3.4.4]

    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:${{ matrix.GODOT_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
        env:
          GODOT_VERSION: ${{ matrix.GODOT_VERSION }}

      - name: Create staging directory
        run: mkdir -v -p build/web

      - name: Build
        run: godot -v --export "HTML5" build/web/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
